name: "PR Build"

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        include:
          - os: ubuntu-latest
            testAdditionalJavaVersions: true
            coverage: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - id: setup-java-8
        name: Setup Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jre
      - id: setup-java-11
        name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: burrunan/gradle-cache-action@v1.10
        with:
          remote-build-cache-proxy-enabled: false
          arguments: check --stacktrace ${{ matrix.coverage && ':opentelemetry-all:jacocoTestReport' || '' }}
          properties: |
            testAdditionalJavaVersions=${{ matrix.testAdditionalJavaVersions }}
            enable.docker.tests=${{ matrix.os == 'ubuntu-latest' }}
            org.gradle.java.installations.paths=${{ steps.setup-java-8.outputs.path }},${{ steps.setup-java-11.outputs.path }}
      - uses: codecov/codecov-action@v1
        if: ${{ matrix.coverage }}
